global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: "rust"
    metrics_path: /metrics
    static_configs:
      - targets: ["rust-service:8080"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
